Parameters:    
  EnvironmentName:
    Type: String
    Default: Dev
  RepositoryName:
    Type: String
Resources:
  DevRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      Tags:
        - Key: env
          Value: !Ref EnvironmentName
Outputs:    
  Arn:
    Value: !GetAtt DevRepository.Arn