pipeline {
    agent any
    environment {
    registry = "https://872354405661.dkr.ecr.us-west-2.amazonaws.com"
    version = "0.0.0"
    }
    stages {
        stage('setup'){
            steps {
                // TODO add stuff here
                sh "chmod +x -R ${env.WORKSPACE}"
                echo "here"
            }
        }
        stage('build') {

            steps {
                dir("app-deploy"){
                    withAWS(credentials:'aws-jenkins-role') {
                        // do something
                        sh 'aws eks --region us-west-2 update-kubeconfig --name develop'
                        
                        sh "./deploy.sh"
                    }

                }
            }
        }

    }
}